### PR TITLE
Pr/2

### PR DESCRIPTION
**Pull request by feefles**
I didn't realize you had committed more things in the last few days, so I went back and cleaned up the previous git history, then added my own.

### CODE REVIEW

**Comment by jabbany** [comment]
LGTM

**Comment by callison-burch** [comment]
FYI, I pushed some change to the repo.  Most of them were content changes, but I removed the _left and _right tags from the staff.yaml and staff.md.

**Comment by feefles** [comment]
Oh great, thanks! Sorry, I didn't know if that would work, probably should have tried first. 
Also, do you want to be on a separate line? like here http://cis.upenn.edu/~cis121/current/staff.shtml

**Comment by callison-burch** [comment]
I’m fine just being part of the grid, unless you prefer it differently.    —CCB

**Pull request merged**
