### PR TITLE
Clarify hw late policy

### PR DESCRIPTION
**Pull request by jabbany**
Open to wording suggestions

### CODE REVIEW

**Comment by jabbany** [comment]
@lyze @feefles

**Comment by feefles** [comment]
I'd like to have @callison-burch 's approval for this change in policy too - seeing as practically every student has interpreted it in this way, and changing it now seems unfair.

**Comment by jabbany** [comment]
To put the "every student" part in perspective: Students in my recitation did not interpret this the other way (25% off their own score) since the policy in this PR is actually the result they see reflected when viewing their grade on the submission page since the beginning of the course. 

That said, I'm not against changing it to be 25% either, but if we do, we also need to assign someone to manually apply the late penalties or send out a notice saying we will not apply any late penalties and just show the raw score then have the students apply it themselves. The infrastructure does not support taking off 25% of the student's grade (vs the assignment total).

**Comment by callison-burch** [comment]
I think that it would be better to use the more liberal interpretation where the students receive higher scores, and then fix the wording for next year.

**Comment by jabbany** [comment]
Makes sense. 

@lyze can you update the DB to remove all the late absolute point score penalties for the previous hws (set them to 0) and then post a clarification on piazza:
- Scores shown on the submissions page do not have late penalties applied.
- Late penalty is 25% off per day: 
  - (0,24h] : Gets 75% of raw grade
  - (24h,48h] : Gets 50% of raw grade
  - (48h, 72h] : Gets 25% of raw grade
  - (72h, infty) : Submissions not accepted (score is 0)
- We apply the late days at the end of the semester to optimize so that their weighted score is highest.

I'm packing to head out for SF in ~1hr. I'll get back Friday morning.

**Comment by feefles** [comment]
Following up, was a Piazza post ever made about this?

**Comment by jabbany** [comment]
I don't think so. That would probably come after removing the current late penalties from the DB (since it doesn't reflect an accurate penalty) which seems to be some work. 

I'll look into that tonight and see if I can remove the late penalty (or maybe set it to 0 etc.) for already deployed hws.

**Comment by feefles** [comment]
Poke

**Comment by jabbany** [comment]
The tables seem to be updated with the late penalties for hws removed. Haven't checked on the submission front end yet though.

**Pull request closed without merging**
